In [3]:
import pandas as pd
import json

# Read the entire JSON file and load all JSON objects
with open('Med Dataset/train.json', 'r') as json_file:
    json_data = json_file.read()

# Split the file content into individual JSON objects
json_objects = json_data.strip().split('\n')

# Convert JSON objects to DataFrames and store them in a list
dataframes = []
for json_obj in json_objects:
    try:
        json_dict = json.loads(json_obj)
        df = pd.DataFrame([json_dict])
        dataframes.append(df)
    except json.JSONDecodeError:
        print(f"Skipping invalid JSON: {json_obj}")

# Concatenate all DataFrames into one
final_dataframe = pd.concat(dataframes, ignore_index=True)

# Save the combined DataFrame to a CSV file
final_dataframe.to_csv('output.csv', index=False)

print("Combined DataFrame saved as output.csv")


Combined DataFrame saved as output.csv


In [7]:
final_dataframe.head(20)

question  \
0   Chronic urethral obstruction due to benign pri...   
1   Which vitamin is supplied from only animal sou...   
2   All of the following are surgical options for ...   
3   Following endaerectomy on the right common car...   
4    Growth hormone has its effect on growth through?   
5      Scrub typhus is transmitted by: September 2004   
6   Abnormal vascular patterns seen with colposcop...   
7   Per rectum examination is not a useful test fo...   
8   Characteristics of Remifentanyl – a) Metabolis...   
9                                      Hypomimia is ?   
10                       Naglers reaction is shown by   
11  Which of the following statements are True/Fal...   
12  The pharmakokinetic change occurring in geriat...   
13                       True regarding lag phase is?   
14  A 60 yr old chronic smoker presents with painl...   
15  With which of the following receptors theophyl...   
16                         Hyper viscosity is seen in   
17  For a positively skewed curve which measure of...   
18  The process of hardening a cement matrix throu...   
19                Superior vena cava is derived from:   

                                                  exp  cop  \
0   Chronic urethral obstruction because of urinar...    3   
1   Ans. (c) Vitamin B12 Ref: Harrison's 19th ed. ...    3   
2   Ans. is 'd' i.e., Roux en Y Duodenal Bypass Ba...    4   
3   The central aery of the retina is a branch of ...    1   
4   Ans. is 'b' i.e., IGI-1GH has two major functi...    2   
5                                    Ans. C i.e. Mite    3   
6   Abnormal vascular pattern include punctation, ...    3   
7   PILONIDAL SINUS/DISEASE (Jeep Bottom; Driver's...    3   
8   Remifentanil is the shortest acting opioid due...    3   
9   Ans. C. Deficit of expression by gestureHypomi...    3   
10  Nagler's reaction - when Clostridium perfringe...    3   
11  Here statement 1 & 3 are wrong. It is actually...    3   
12  One of the most impoant pharmacokinetic change...    3   
13  Lag phase: Immediately following the seeding o...    1   
14  Urine microscopy for malignant cytology "Painl...    4   
15                                               None    3   
16  Ref William hematology 6/e p1268 The term cryo...    1   
17  A distribution is negatively skewed, or skewed...    1   
18  Maturation (cement)—The process of hardening a...    1   
19  Ans. C Cardinal veinRef; hangman's essesntial ...    3   

                                          opa                          opb  \
0                                 Hyperplasia                    Hyperophy   
1                                   Vitamin C                   Vitamin B7   
2                  Adjustable gastric banding    Biliopancreatic diversion   
3                  Central aery of the retina            Infraorbital aery   
4                                    Directly                        IG1-1   
5                                       Louse                         Tick   
6                                  Punctation                    Mosaicism   
7                                Anal fissure                   Hemorrhoid   
8                                          ab                           bc   
9                   Decreased ability to copy          Decreased execution   
10                         Clostridium tetani        Clostridium botulinum   
11                  1, 2, 3 True & 4, 5 false    1, 3, 5 True & 2, 4 false   
12                         Gastric absorption             Liver metabolism   
13  Time taken to adpt in the new environment  Growth occurs exponentially   
14                                        USG                    X-ray KUB   
15                        Histamine receptors         Bradykinin receptors   
16                           Cryoglobulinemia             Multiple myeloma   
17                                       Mean                         Mode   
18                                 Maturation                 

In [5]:
df=pd.read_csv('output.csv')

In [6]:
df['difficulty']=0

In [14]:
df.head()

cop                                    id  choice_type  difficulty  \
0    3  e9ad821a-c438-4965-9f77-760819dfa155            1           0   
1    3  e3d3c4e1-4fb2-45e7-9f88-247cc8f373b3            1           0   
2    4  5c38bea6-787a-44a9-b2df-88f4218ab914            0           0   
3    1  cdeedb04-fbe9-432c-937c-d53ac24475de            0           0   
4    2  dc6794a3-b108-47c5-8b1b-3b4931577249            1           0   

   corr_ab  corr_ac  corr_ad  corr_bc  corr_bd  corr_cd  
0        0        0        0        0        0        0  
1        0        0        0        0        0        0  
2        0        0        0        0        0        0  
3        0        0        0        0        0        0  
4        0        0        0        0        0        0

In [9]:
df=df.drop(['question'],axis=1)
df=df.drop(['exp'],axis=1)
df=df.drop(['opa'],axis=1)
df=df.drop(['opb'],axis=1)
df=df.drop(['opc'],axis=1)
df=df.drop(['opd'],axis=1)
df=df.drop(['subject_name'],axis=1)
df=df.drop(['topic_name'],axis=1)


In [11]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df['choice_type'] = label_encoder.fit_transform(df['choice_type'])

In [13]:
df['corr_ab']=0
df['corr_ac']=0
df['corr_ad']=0
df['corr_bc']=0
df['corr_bd']=0
df['corr_cd']=0

In [18]:
final_dataframe['topic_name'].nunique()


2388

In [36]:
import pandas as pd
df=pd.read_csv("output.csv")

In [37]:
df.head()

question  \
0  Chronic urethral obstruction due to benign pri...   
1  Which vitamin is supplied from only animal sou...   
2  All of the following are surgical options for ...   
3  Following endaerectomy on the right common car...   
4   Growth hormone has its effect on growth through?   

                                                 exp  cop  \
0  Chronic urethral obstruction because of urinar...    3   
1  Ans. (c) Vitamin B12 Ref: Harrison's 19th ed. ...    3   
2  Ans. is 'd' i.e., Roux en Y Duodenal Bypass Ba...    4   
3  The central aery of the retina is a branch of ...    1   
4  Ans. is 'b' i.e., IGI-1GH has two major functi...    2   

                          opa                        opb              opc  \
0                 Hyperplasia                  Hyperophy          Atrophy   
1                   Vitamin C                 Vitamin B7      Vitamin B12   
2  Adjustable gastric banding  Biliopancreatic diversion  Duodenal Switch   
3  Central aery of the retina          Infraorbital aery    Lacrimal aery   
4                    Directly                      IG1-1        Thyroxine   

                          opd   subject_name                  topic_name  \
0                    Dyplasia        Anatomy               Urinary tract   
1                   Vitamin D   Biochemistry       Vitamins and Minerals   
2  Roux en Y Duodenal By pass        Surgery  Surgical Treatment Obesity   
3          Nasociliary aretry  Ophthalmology                         NaN   
4      Intranuclear receptors     Physiology                         NaN   

                                     id choice_type  
0  e9ad821a-c438-4965-9f77-760819dfa155      single  
1  e3d3c4e1-4fb2-45e7-9f88-247cc8f373b3      single  
2  5c38bea6-787a-44a9-b2df-88f4218ab914       multi  
3  cdeedb04-fbe9-432c-937c-d53ac24475de       multi  
4  dc6794a3-b108-47c5-8b1b-3b4931577249      single

In [38]:
df=df.drop(['question'],axis=1)
df=df.drop(['exp'],axis=1)
df=df.drop(['opa'],axis=1)
df=df.drop(['opb'],axis=1)
df=df.drop(['opc'],axis=1)
df=df.drop(['opd'],axis=1)
df=df.drop(['subject_name'],axis=1)
df=df.drop(['topic_name'],axis=1)
df=df.drop(['cop'],axis=1)
df=df.drop(['id'],axis=1)
df=df.drop(['choice_type'],axis=1)


In [39]:
import random
import numpy as np

df['Difficulty'] = np.random.uniform(0, 100, size=len(df))
df['Time_Spent'] = np.random.randint(0, 100, size=len(df))
df['Activity_score'] = np.random.uniform(0, 100, size=len(df))
df['Normalized_score'] = np.random.randint(1, 10, size=len(df))


In [40]:
df.head()

Difficulty  Time_Spent  Activity_score  Normalized_score
0   72.604834          66       50.619464                 1
1    2.381044          65       54.390855                 1
2   72.299228          31       43.962328                 6
3   59.705270          43       88.345687                 5
4   12.940263          65       67.794164                 9

In [42]:
df.to_csv('test1.csv')

In [45]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Assuming 'df' is your DataFrame with the columns 'Difficulty', 'Time_Spent', 'Activity_score', 'Normalized_score'

# Step 2: Preprocess the data
X = df[['Difficulty', 'Time_Spent', 'Activity_score']]  # Features
y = df['Normalized_score']  # Target variable

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Train the logistic regression model
model = LogisticRegression(max_iter=1000)  # Increase max_iter if needed for convergence
model.fit(X_train, y_train)

# Step 4: Evaluate the model
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Display confusion matrix and classification report
conf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(conf_matrix)

class_report = classification_report(y_test, y_pred)
print('Classification Report:')
print(class_report)


Accuracy: 0.11218378230548338
Confusion Matrix:
[[   0   63 1292  443  370  404    0    0 1510]
 [   0   75 1271  405  367  442    0    0 1486]
 [   0   66 1262  444  354  405    0    0 1511]
 [   0   67 1243  446  347  444    0    0 1519]
 [   0   66 1246  459  382  437    0    0 1463]
 [   0   62 1231  464  362  410    0    0 1453]
 [   0   68 1258  471  367  426    0    0 1504]
 [   0   75 1320  431  345  424    0    0 1503]
 [   0   75 1265  443  361  431    0    0 1527]]
Classification Report:
              precision    recall  f1-score   support

           1       0.00      0.00      0.00      4082
           2       0.12      0.02      0.03      4046
           3       0.11      0.31      0.16      4042
           4       0.11      0.11      0.11      4066
           5       0.12      0.09      0.10      4053
           6       0.11      0.10      0.11      3982
           7       0.00      0.00      0.00      4094
           8       0.00      0.00      0.00      4098
         

c:\Users\anish\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\anish\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\anish\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

In [44]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Assuming 'df' is your DataFrame with the columns 'Difficulty', 'Time_Spent', 'Activity_score', 'Normalized_score'

# Step 2: Preprocess the data
X = df[['Difficulty', 'Time_Spent', 'Activity_score']]  # Features
y = df['Normalized_score']  # Target variable

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Train the Random Forest model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Step 4: Evaluate the model
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy:', accuracy)

# Display confusion matrix and classification report
conf_matrix = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(conf_matrix)

class_report = classification_report(y_test, y_pred)
print('Classification Report:')
print(class_report)


Accuracy: 0.11119923424039382
Confusion Matrix:
[[493 454 486 449 418 441 470 426 445]
 [439 428 465 478 458 451 422 456 449]
 [464 448 431 485 433 462 463 431 425]
 [442 467 460 475 438 496 430 419 439]
 [444 442 479 474 438 470 432 471 403]
 [459 424 448 442 415 450 492 403 449]
 [463 458 473 466 472 423 467 426 446]
 [476 462 454 463 449 429 450 435 480]
 [457 470 489 462 475 425 466 409 449]]
Classification Report:
              precision    recall  f1-score   support

           1       0.12      0.12      0.12      4082
           2       0.11      0.11      0.11      4046
           3       0.10      0.11      0.10      4042
           4       0.11      0.12      0.12      4066
           5       0.11      0.11      0.11      4053
           6       0.11      0.11      0.11      3982
           7       0.11      0.11      0.11      4094
           8       0.11      0.11      0.11      4098
           9       0.11      0.11      0.11      4102

    accuracy                       

In [46]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.metrics import mean_squared_error

# Assuming 'df' is your DataFrame with the columns 'Difficulty', 'Time_Spent', 'Activity_score', 'Normalized_score'

# Step 2: Preprocess the data
X = df[['Difficulty', 'Time_Spent', 'Activity_score']]  # Features
y = df['Normalized_score']  # Target variable

# Normalize features to be in the range [0, 1]
scaler = MinMaxScaler()
X_normalized = scaler.fit_transform(X)

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X_normalized, y, test_size=0.2, random_state=42)

# Step 3: Build the neural network model
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dropout(0.3))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(1))  # Output layer (1 neuron for regression)

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Step 4: Train the neural network model
model.fit(X_train, y_train, epochs=50, batch_size=32, verbose=1)

# Step 5: Evaluate the model
y_pred = model.predict(X_test)

# Calculate Mean Squared Error (MSE)
mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)


Epoch 1/50
4571/4571 [==============================] - 8s 2ms/step - loss: 7.6957
Epoch 2/50
4571/4571 [==============================] - 8s 2ms/step - loss: 7.0121
Epoch 3/50
4571/4571 [==============================] - 7s 2ms/step - loss: 6.8546
Epoch 4/50
4571/4571 [==============================] - 7s 2ms/step - loss: 6.7784
Epoch 5/50
4571/4571 [==============================] - 8s 2ms/step - loss: 6.7299
Epoch 6/50
4571/4571 [==============================] - 9s 2ms/step - loss: 6.7039
Epoch 7/50
4571/4571 [==============================] - 7s 2ms/step - loss: 6.6861
Epoch 8/50
4571/4571 [==============================] - 7s 2ms/step - loss: 6.6767
Epoch 9/50
4571/4571 [==============================] - 7s 2ms/step - loss: 6.6691
Epoch 10/50
4571/4571 [==============================] - 7s 2ms/step - loss: 6.6651
Epoch 11/50
4571/4571 [==============================] - 7s 2ms/step - loss: 6.6652
Epoch 12/50
4571/4571 [==============================] - 7s 2ms/step - loss: 6.6603
E

In [47]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ReduceLROnPlateau
from sklearn.metrics import mean_squared_error

# Assuming 'df' is your DataFrame with the columns 'Difficulty', 'Time_Spent', 'Activity_score', 'Normalized_score'

# Step 2: Preprocess the data
X = df[['Difficulty', 'Time_Spent', 'Activity_score']]  # Features
y = df['Normalized_score']  # Target variable

# Normalize features to be in the range [0, 1]
scaler = MinMaxScaler()
X_normalized = scaler.fit_transform(X)

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X_normalized, y, test_size=0.2, random_state=42)

# Step 3: Build the neural network model
model = Sequential()
model.add(Dense(128, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(1))  # Output layer (1 neuron for regression)

# Compile the model with a lower learning rate
optimizer = Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='mean_squared_error')

# Implement learning rate reduction
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=5, min_lr=0.0001)

# Step 4: Train the neural network model
model.fit(X_train, y_train, epochs=50, batch_size=32, verbose=1, validation_split=0.1, callbacks=[reduce_lr])

# Step 5: Evaluate the model
y_pred = model.predict(X_test)

# Calculate Mean Squared Error (MSE)
mse = mean_squared_error(y_test, y_pred)
print('Mean Squared Error:', mse)


Epoch 1/50
4114/4114 [==============================] - 8s 2ms/step - loss: 7.4151 - val_loss: 6.8321 - lr: 0.0010
Epoch 2/50
4114/4114 [==============================] - 8s 2ms/step - loss: 6.9334 - val_loss: 6.7164 - lr: 0.0010
Epoch 3/50
4114/4114 [==============================] - 8s 2ms/step - loss: 6.8329 - val_loss: 6.7087 - lr: 0.0010
Epoch 4/50
4114/4114 [==============================] - 8s 2ms/step - loss: 6.7858 - val_loss: 6.7074 - lr: 0.0010
Epoch 5/50
4114/4114 [==============================] - 8s 2ms/step - loss: 6.7509 - val_loss: 6.7151 - lr: 0.0010
Epoch 6/50
4114/4114 [==============================] - 8s 2ms/step - loss: 6.7380 - val_loss: 6.7205 - lr: 0.0010
Epoch 7/50
4114/4114 [==============================] - 9s 2ms/step - loss: 6.7119 - val_loss: 6.7153 - lr: 0.0010
Epoch 8/50
4114/4114 [==============================] - 9s 2ms/step - loss: 6.7043 - val_loss: 6.7089 - lr: 0.0010
Epoch 9/50
4114/4114 [==============================] - 8s 2ms/step - loss: 6.70

KeyboardInterrupt: 

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, r2_score

# Load your DataFrame (assuming it's named 'df')
# Replace this with loading your actual DataFrame
# df = ...

# Assuming df is already loaded and contains the relevant columns

# Step 1: Prepare the Data
X = df[['Difficulty', 'Time_Spent', 'Activity_score']]
y = df['Normalized_score']

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 2: Feature Scaling with Min-Max Scaler
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Dictionary to store results
results = {}

# Models to evaluate
models = {
    'Linear Regression': LinearRegression(),
    'Decision Tree': DecisionTreeRegressor(random_state=42),
    'Random Forest': RandomForestRegressor(random_state=42),
    'Gradient Boosting': GradientBoostingRegressor(random_state=42),
    'SVR': SVR()
}

# Train and evaluate each model
for model_name, model in models.items():
    # Train the model
    model.fit(X_train_scaled, y_train)
    
    # Predict on the test set
    y_pred = model.predict(X_test_scaled)
    
    # Calculate mean squared error and R-squared
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    
    # Store results
    results[model_name] = {'Mean Squared Error': mse, 'R-squared': r2}

# Display the results
for model_name, metrics in results.items():
    print(f"Model: {model_name}")
    print(f"Mean Squared Error: {metrics['Mean Squared Error']:.2f}")
    print(f"R-squared: {metrics['R-squared']:.2f}")
    print("\n")


In [30]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, r2_score

# Load your DataFrame (assuming it's named 'df')
# Replace this with loading your actual DataFrame
# df = ...

# Assuming df is already loaded and contains the relevant columns

# Step 1: Prepare the Data
X = df[['Difficulty', 'Time_Spent', 'Activity_score']]
y = df['Normalized_score']

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 2: Feature Scaling
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 3: Train the Model (using Linear Regression in this example)
model = SVR()
model.fit(X_train_scaled, y_train)

# Step 4: Evaluate the Model
# Predict on the test set
y_pred = model.predict(X_test_scaled)

# Calculate mean squared error and R-squared
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)


KeyboardInterrupt: 